name: Custom Modifications

on:
  workflow_dispatch:
  # This workflow can be manually triggered and also runs before other workflows
  workflow_call:
    # Allow it to be called by other workflows

jobs:
  modify-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository files:"
          ls -la

      - name: Replace URLs and Modify Code
        run: |
          # Replace all URLs from 281677160/common to ydfk/openwrt-common
          find . -type f -name "*.sh" -exec sed -i 's|/281677160/common|/ydfk/openwrt-common|g' {} \;
          
          # Fix syntax errors in common.sh
          if [ -f "common.sh" ]; then
            echo "Fixing syntax errors in common.sh"
            # Fix missing 'fi' in LIENOL section
            sed -i '/function Diy_IMMORTALWRT/,/^}/{ s/^fi$//; }' common.sh
            sed -i '/LIENOL)/,/IMMORTALWRT)/s/  elif \[\[ "\${REPO_BRANCH}" == "21\.02" \]\]; then/  elif \[\[ "\${REPO_BRANCH}" == "21\.02" \]\]; then\n    s="luci-app-unblockneteasemusic"\n    c=(\${s//,\/ \/})\n    for i in \${c\[@\]}; do \\\n      find . -type d -name "\${i}" |grep -v '\''freifunk\\|helloworld\\|passwall3'\'' |xargs -i rm -rf {}; \\\n    done\n    fi/g' common.sh
            sed -i '/LIENOL)/,/IMMORTALWRT)/s/  elif \[\[ "\${REPO_BRANCH}" == "23\.05" \]\]; then/  elif \[\[ "\${REPO_BRANCH}" == "23\.05" \]\]; then\n    s="luci-app-unblockneteasemusic"\n    c=(\${s//,\/ \/})\n    for i in \${c\[@\]}; do \\\n      find . -type d -name "\${i}" |grep -v '\''freifunk\\|helloworld\\|passwall3'\'' |xargs -i rm -rf {}; \\\n    done/g' common.sh
            sed -i '/OFFICIAL)/,/XWRT)/s/  if \[\[ "\${REPO_BRANCH}" == "openwrt-21\.02" \]\]; then/  if \[\[ "\${REPO_BRANCH}" == "openwrt-21\.02" \]\]; then\n    s="luci-app-vssr,lua-maxminddb,luci-app-natter,natter,luci-app-unblockneteasemusic"\n    c=(\${s//,\/ \/})\n    for i in \${c\[@\]}; do \\\n      find . -type d -name "\${i}" |grep -v '\''freifunk\\|helloworld\\|passwall3'\'' |xargs -i rm -rf {}; \\\n    done\n    if \[\[ -d "\${HOME_PATH}\/build\/common\/Share\/luci-app-samba4" \]\]; then\n      find . -type d -name '\''luci-app-samba4'\'' -o -name '\''samba4'\'' |grep -v '\''Share\\|freifunk\\|helloworld\\|passwall3'\'' | xargs -i rm -rf {}\n      cp -Rf \${HOME_PATH}\/build\/common\/Share\/luci-app-samba4 \${HOME_PATH}\/feeds\/luci\/applications\/luci-app-samba4\n      cp -Rf \${HOME_PATH}\/build\/common\/Share\/samba4 \${HOME_PATH}\/feeds\/packages\/net\/samba4\n      rm -rf \${HOME_PATH}\/feeds\/packages\/libs\/liburing\n      cp -Rf \${HOME_PATH}\/build\/common\/Share\/liburing \${HOME_PATH}\/feeds\/packages\/libs\/liburing\n      rm -rf \${HOME_PATH}\/feeds\/packages\/lang\/perl-parse-yapp\n      cp -Rf \${HOME_PATH}\/build\/common\/Share\/perl-parse-yapp \${HOME_PATH}\/feeds\/packages\/lang\/perl-parse-yapp\n    fi\n    fi/g' common.sh
            # Other specific changes to common.sh here
          fi
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Replace URLs and make custom modifications"
            git push
            echo "Changes committed and pushed"
          else
            echo "No changes to commit"
          fi